arduino-libraries/ArduinoBearSSL

- src/BearSSLClient.h
add BEAR_SSL_CLIENT_IOBUF_SIZE so that user can define it as a build option to have different IOBUF_SIZE
> #define BEAR_SSL_CLIENT_IOBUF_SIZE

- src/BearSSLClient.cpp
- src/BearSSLClient.h
An alternative proposal for #14.
> Allow built-in trust anchors to be overrided via constructor

- src/BearSSLClient.cpp
- src/BearSSLClient.h
Add support for not sending [Server Name Indication](https://en.wikipedia.org/wiki/Server_Name_Indication) even when host is a DNS name.
This PR paves the way for supporting TLS servers with home-made/self-created PKI CAs and no SNI extension in server certificate.
This PR has been tested on an Arduino MKR WiFi 1000 and an Arduino MKR WiFi 1010 connected to an in-house MQTT/S broker ([mosquitto](https://mosquitto.org/)) with TLS support configured with security files generated via an in-house [EasyRSA](https://github.com/OpenVPN/easy-rsa) instance.
The Arduino boards have been programmed with the [AWS_IoT_WiFi.ino](https://github.com/arduino/ArduinoCloudProviderExamples/blob/master/examples/AWS%20IoT/AWS_IoT_WiFi/AWS_IoT_WiFi.ino) sketch.
Certificates generation steps:
* the certificate …
> Add support for not sending any SNI

- src/BearSSLClient.cpp
Fix local TA + implicit noSNI constructor (`BearSSLClient(Client& client, const br_x509_trust_anchor* myTAs, int myNumTAs);`).
That was a regression introduced by https://github.com/arduino-libraries/ArduinoBearSSL/pull/19.
> Fix local TA + implicit noSNI constructor

- src/BearSSLClient.cpp
- src/BearSSLClient.h
Use two dedicated buffers for input and output instead of split mode,
indeed some MQTT server (especially with TLS) needs a full 8k buffer as
they send their Certificate Chain. On the other hand, on output, a 1k
buffer seems to be enough
Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
> Use two buffers instead of one buffer in split mode

- .github/workflows/compile-examples.yml
- .github/workflows/report-size-deltas.yml
- .github/workflows/spell-check.yml
- On every pull request and push, compile appropriate examples for MKR1000, MKRGSM, Uno WiFi Rev2
- Comment on pull requests with a report of how the proposed changes affect memory usage
- Check all files, except the external resource src/bearssl, for commonly misspelled words.
- In the event of false positives, add the word (in lower case) to extras/codespell-ignore-words-list.txt.
Although the ArduinoBearSSL library specifies compatibility with all architectures, its ArduinoECCX08 library dependency specifies only SAMD and megaAVR compatibility. I used boards of those architectures in the compilation tests.
Demonstration run of the compile-examples workflow:
https://github.com/per1234/ArduinoBearSSL/actions/runs/115758283
Demonstration run of the spell-check workflow: …
> Use GitHub actions for continuous integration

- README.adoc
These badges show the status of the most recent CI workflow runs for the default branch.
Fixes https://github.com/arduino-libraries/ArduinoBearSSL/issues/27 (sorry, I always forget the badges)
> Add CI status badges to readme

- examples/extras/WiFiSSLClientNoSNI/WiFiSSLClientNoSNI.ino
- src/BearSSLClient.cpp
- src/BearSSLClient.h
Alternative implementation for https://github.com/arduino-libraries/ArduinoBearSSL/pull/19.
@endorama please, review.
> Safer implementation of no-SNI connection method

- src/BearSSLClient.cpp
- src/BearSSLClient.h
This allows for the ArduinoIoTCloud firmware to intantiate ArduinoBearSSL on the stack instead of the heap.
> Adding an additional BearSSL constructor as well as a method setClient to allow late initialisation.

- examples/MD5/MD5.ino
- src/ArduinoBearSSL.h
- src/MD5.cpp
- src/MD5.h
I have added MD5 API's and an example.
> Add MD5 API and example

- src/BearSSLClient.cpp
- src/BearSSLClient.h
Add _ecVrfy and _ecSign to allow the user to customize the verification
and signature functions (could be useful if the user wants to use
BearSSLClient without ECC508)
The functions can be customized through the constructor and are set to
their current values as soon as the user calls setEccSlot
> Add _ecVrfy and _ecSign

- src/BearSSLClient.cpp
- src/BearSSLClient.h
This will allow the user to use ArduinoBearSSL without the ECCX08 (for
example with an (e)SIM applet compliant to the new GSMA IoT SAFE standard)
> Allow the user to set his own client certificate

- examples/AES128/AES128.ino
- examples/DES/DES.ino
- src/AES128.cpp
- src/AES128.h
- src/DES.cpp
- src/DES.h
- src/Encryption.cpp
- src/Encryption.h
I have added user-friendly (I hope) support to symmetric encryption. In particular, you can run DES and AES128 now.
Giving the secret key, the initialization vector and the plain text, this method returns the encrypted one.
**Syntax**
`AES128.runEnc(key, keyLength, input, inputLengh, iv);`
**Parameters**
- *key*: the secret key used to encrypt the plain text. The variable type is `uint8_t`;
- *keyLength*: the secret key's length. It is *always* 16. The variable type is `size_t`;
- *input*: the plain text. The variable type is `uint8_t`;
- *inputLengh*: the plain text's length. It must be *always* a multiple of 16. The variable type is `size_t`;
- *iv*: the initialization vector. It must have *always* 16 bytes. The variable type is `uint8_t`;
**Example**
```
#include <ArduinoBearSSL.h> …
```
> Adding symmetric encryption

- src/BearSSLClient.cpp
The client can specify its own `_ecSign` function since commit 996778e73d22093526b1b7126cf7bfc2499158b5 as well as its own certificate since commit 874c6b0c38ae2ad34a3388710961411e3a3aed5a.
The goal was to allow the user to use ArduinoBearSSL without the ECCX08 (for example with an (e)SIM applet compliant to the new GSMA IoT SAFE standard).
However, these two functions don't work because `br_ssl_client_set_single_ec` is not called if `_ecKey.xlen` is set to 0 so fix this latest issue
> src/BearSSLClient.cpp: fix _ecSign

- .codespellrc
- .github/workflows/compile-examples.yml
- .github/workflows/report-size-deltas.yml
- .github/workflows/spell-check.yml
Some advancements have been made in the GitHub Actions actions and workflows used by this repository since the time the CI system was originally set up. This PR brings them back to state of the art status again.
> Update CI workflows to modern standards

- src/BearSSLClient.cpp
- src/BearSSLClient.h
This will allow the user to specify a client certificate chain instead of a single client certificate.
This is useful for example for AWS just-in-time registration or Just-in-time provisioning (JITP):
https://aws.amazon.com/blogs/iot/just-in-time-registration-of-device-certificates-on-aws-iot
https://docs.aws.amazon.com/iot/latest/developerguide/jit-provisioning.html
> Add setEccChain function

- src/BearSSLClient.cpp
- src/BearSSLClient.h
This is similar to #39 in that it enables setting the parent certificate of a client certificate, but the difference to #39 is that it works when the client certificate private key is using an ECC508/608 key slot.
This change is based from #43 and with these two changes it makes it possible to use AWS JITP with an Arduino Nano 33 IoT with the private key stored in the ATECC608A.
> Enable setting client certificate parent

- src/BearSSLClient.cpp
Fix for https://github.com/arduino-libraries/ArduinoBearSSL/issues/42
> Use original sign and verify functions as default

- README.adoc
- examples/AES128/ArduinoBearSSLConfig.h
- examples/DES/ArduinoBearSSLConfig.h
- examples/MD5/ArduinoBearSSLConfig.h
- examples/MKRGSMSSLClient/ArduinoBearSSLConfig.h
- examples/SHA1/ArduinoBearSSLConfig.h
- examples/SHA256/ArduinoBearSSLConfig.h
- examples/WiFiSSLClient/ArduinoBearSSLConfig.h
- examples/extras/WiFiSSLClientNoSNI/ArduinoBearSSLConfig.h
- src/ArduinoBearSSL.h
- src/BearSSLClient.cpp
- src/utility/eccX08_sign_asn1.cpp
- src/utility/eccX08_vrfy_asn1.cpp
This new compilation flag can be set through ArduinoBearSSLConfig.h and
will allow the user to use ArduinoBearSSL without ECCX08.
Indeed, the cryptographic operations could be done through the default
software implementation or offloaded to another secure element such as
an applet compliant with the GSMA IoT SAFE standard.
> Add ARDUINO_DISABLE_ECCX08

- .github/dependabot.yml
- .github/workflows/check-arduino.yml
- .github/workflows/compile-examples.yml
- .github/workflows/report-size-deltas.yml
- README.adoc
This PR updates the CI system to the standardized [GitHub Actions](https://github.com/features/actions)-based CI configuration for Arduino libraries.
Dependabot will periodically check the versions of all actions used in the repository's workflows. If any are found to be outdated, it will submit a pull request to update them.
NOTE: Dependabot's PRs will sometimes try to pin to the patch version of the action (e.g., updating `uses: foo/bar@v1` to `uses: foo/bar@v2.3.4`). When the action author has [provided a major version ref](https://docs.github.com/en/actions/creating-actions/about-actions#using-release-management-for-actions), use that instead (e.g., `uses: foo/bar@v2`). Once the major version has been updated in the workflow, Dependabot should not submit an update PR again until the …
> Update continuous integration system

- src/BearSSLClient.cpp
This PR resolves the issue(#60): failed to send a long date ( > 512 bytes ).
> fix write() in BearSSLClient.cpp
